# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\script\ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 500)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(1, 0, 400, 500))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setEnabled(True)
        self.tab_1.setObjectName("tab_1")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_1)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(130, 260, 141, 112))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.run_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.run_button.setObjectName("run_button")
        self.verticalLayout_2.addWidget(self.run_button)
        self.stop_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.stop_button.setObjectName("stop_button")
        self.verticalLayout_2.addWidget(self.stop_button)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.quit_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.quit_button.setObjectName("quit_button")
        self.verticalLayout_2.addWidget(self.quit_button)
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_1)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(100, 90, 191, 141))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.flow_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.flow_label.setText("")
        self.flow_label.setObjectName("flow_label")
        self.gridLayout.addWidget(self.flow_label, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.user_name_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.user_name_label.setText("")
        self.user_name_label.setObjectName("user_name_label")
        self.gridLayout.addWidget(self.user_name_label, 2, 1, 1, 1)
        self.login_status_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.login_status_label.setText("")
        self.login_status_label.setObjectName("login_status_label")
        self.gridLayout.addWidget(self.login_status_label, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.run_status_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.run_status_label.setText("")
        self.run_status_label.setObjectName("run_status_label")
        self.gridLayout.addWidget(self.run_status_label, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.user_info_table = QtWidgets.QTableWidget(self.tab_3)
        self.user_info_table.setGeometry(QtCore.QRect(7, 30, 380, 390))
        self.user_info_table.setObjectName("user_info_table")
        self.user_info_table.setColumnCount(2)
        self.user_info_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_info_table.setHorizontalHeaderItem(1, item)
        self.user_list_update_button = QtWidgets.QPushButton(self.tab_3)
        self.user_list_update_button.setGeometry(QtCore.QRect(160, 440, 75, 23))
        self.user_list_update_button.setObjectName("user_list_update_button")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 54, 12))
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.quit_button.clicked.connect(MainWindow.close)
        self.run_button.clicked.connect(MainWindow.run_auto_login)
        self.user_list_update_button.clicked.connect(MainWindow.list_update)
        self.stop_button.clicked.connect(MainWindow.stop_auto_login)
        self.pushButton.clicked.connect(MainWindow.minimize)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UCAS 校园网自动登陆"))
        self.run_button.setText(_translate("MainWindow", "开始运行"))
        self.stop_button.setText(_translate("MainWindow", "停止运行"))
        self.pushButton.setText(_translate("MainWindow", "最小化到托盘"))
        self.quit_button.setText(_translate("MainWindow", "退出程序"))
        self.label_3.setText(_translate("MainWindow", "当前用户"))
        self.label_6.setText(_translate("MainWindow", "剩余流量"))
        self.label.setText(_translate("MainWindow", "登录状态"))
        self.label_2.setText(_translate("MainWindow", "运行状态"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "自动登录"))
        item = self.user_info_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "用户名"))
        item = self.user_info_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "剩余流量"))
        self.user_list_update_button.setText(_translate("MainWindow", "更新名单"))
        self.label_4.setText(_translate("MainWindow", "当前可用"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "用户名单"))

